#-------------------------------
# Site Settings
title: Strong Towns Nanaimo - People, Not Cars
header_title: Strong Towns Nanaimo
logo: # /images/logo-header.png
description: Everyone deserves to live in an affordable, equitable, and financially secure city. Decades of auto-oriented, sprawling development have left their mark on Nanaimo, leading to expensive housing, unproductive urban spaces, and unsafe streets. Together, we can advocate for a city built around people, not automobiles.

#-------------------------------
# Author Global Settings
author:
  author__name: Strong Towns Nanaimo
  author__bio: Strong Towns Nanaimo advocates for a new approach to urban planning and development that is financially resilient, sustainable, and equitable. We are a grassroots organization that is not affiliated with the City of Nanaimo.  Everyone deserves to live in an affordable, equitable, and financially secure city. Decades of auto-oriented, sprawling development have left their mark on Nanaimo, leading to expensive housing, unproductive urban spaces, and unsafe streets. Together, we can advocate for a city built around people, not automobiles.
  author__avatar: /images/logo-small.png

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Articles'
      url: '/articles'
    - url: '/events'
      title: 'Events'
    - title: 'About'
      url: '/about'
    - title: 'Campaigns'
      submenu:
        - title: 'Parking'
          url: '/parking'
    - title: 'More'
      submenu:
      - title: 'Contact'
        url: '/contact'
      - url: '/members'
        title: 'Members'
      - url: '/library'
        title: 'Library'
      - url: '/media'
        title: 'Media'

#-------------------------------
# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Articles'
      url: '/articles'
    - title: 'Events'
      url: '/events'
    - title: 'About'
      url: '/about'
    - title: 'Parking'
      url: '/parking'
    - title: 'Contact'
      url: '/contact'
    - title: 'Members'
      url: '/members'
    - title: 'Library'
      url: '/library'
    - title: 'Media'
      url: '/media'

#-------------------------------
# Hero Settings
hero:
  hero__title: Everyone deserves to live in an <i>affordable, equitable, and financially secure city</i>. Decades of auto-oriented, sprawling development have left their mark on Nanaimo, leading to expensive housing, unproductive urban spaces, and unsafe streets. Together, we can advocate for a city built around <i>people, not automobiles</i>.

#-------------------------------
# Blog Settings
blog:
  blog__title: Features, Articles & News
  blog__description: Learn More About Strong Towns Nanaimo

#
# Calendar Settings
calendar:
  calendar__title: Strong Towns Nanaimo Events Calendar
  calendar__description: Subscribe to our Calendar so You'll Never Miss an Event

#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Recommended
  tag__name: Safety

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp__identifier: https://bc2089c3.sibforms.com/serve/MUIEAAOSzKqSStZTACBWK2hNIl9ucHbLHSaGl7WNZJmVN_PdDJhkurSKDCy-OMSXhBltjlYSTXwpczGV37Gh7hQBqjp6NeZXKX10XITizKUnQTPu6zjzXEQFvBFY2t0M9D9ns1CME7K5967yMGjvgd8UVUpsbifrLSMyKAfggTkxrjjbWl8IA0CfvFIi034MwIsxNzj0Gv_gWcAU
  mailchimp__title: Connect With Us
  mailchimp__description: Subscribe to our newsletter and we'll send you emails of new posts. We promise we'll never spam your inbox.
  mailchimp__input__text: Your Email Address
  mailchimp__button__text: Connect
  mailchimp__background__image: "/images/nanaimo-photos/nanaimo-harbour-3.jpg"

# Social Links
social:
- {icon: "ion-ios-chatboxes", color: "#0a243f", name: Discord, link: "https://discord.gg/rz9VwsegS6"}
- {icon: "ion-logo-linkedin", color: "#0a243f", name: LinkedIn, link: "https://www.linkedin.com/company/STNanaimo/"}
- {icon: "ion-logo-twitter", color: "#0a243f", name: Twitter, link: "https://bsky.app/profile/stnanaimo.bsky.social"}
- {icon: "ion-logo-rss", color: "#0a243f", name: RSS, link: "/feed.xml"}

# Example of adding a new link to the footer - {icon: "ion-logo-youtube", color: "#ff0000", name: Youtube, link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: mleknryo  # Email generated from Formspree

#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: strong-towns-nanaimo

#-------------------------------
# Google Analytics
# NOTE We're using Cloudflare instead...
google-analytics: # Add your GA Tracking Id