#-------------------------------
# Site Settings
title: Strong Towns Nanaimo
logo: # NOTE Add logo to replace the title...
description: Everyone deserves to live in a beautiful, financially secure city. We all have a role in fixing our city. Together, we can transform Nanaimo into a vibrant city!



#-------------------------------
# Author Global Settings
author:
  author__name: Strong Towns Nanaimo
  author__bio: Strong Towns Nanaimo advocates for a new approach to urban planning and development that is financially resilient, sustainable, and equitable. We all have a role in fixing our city. Together, we can transform Nanaimo into a vibrant city!
  author__avatar: /images/logo-small.png


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Pages'
      submenu:
      - url: '/meetings/'
        title: 'Meetings'
      - url: '/library/'
        title: 'Library'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Everyone deserves to live in a beautiful, financially secure city. Decades of auto-oriented development has left its mark on Nanaimo, leading to unpleasant, unsafe, and financially unproductive urban spaces. We all have a role in fixing our city. Together, we can transform Nanaimo into a vibrant city!


#-------------------------------
# Blog Settings
blog:
  blog__title: Blog & Resources
  blog__description: Learn About Strong Towns


#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Recommended
  tag__name: Safety


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp__identifier: https://bc2089c3.sibforms.com/serve/MUIEAAOSzKqSStZTACBWK2hNIl9ucHbLHSaGl7WNZJmVN_PdDJhkurSKDCy-OMSXhBltjlYSTXwpczGV37Gh7hQBqjp6NeZXKX10XITizKUnQTPu6zjzXEQFvBFY2t0M9D9ns1CME7K5967yMGjvgd8UVUpsbifrLSMyKAfggTkxrjjbWl8IA0CfvFIi034MwIsxNzj0Gv_gWcAU
  mailchimp__title: Connect With Us
  mailchimp__description: Subscribe to our newsletter and we'll send you emails of new posts. We promise we'll never spam your inbox.
  mailchimp__input__text: Your Email Address
  mailchimp__button__text: Connect
  mailchimp__background__image: "/images/nanaimo-photos/nanaimo-harbour-3.jpg"


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Meetings'
      url: '/meetings/'
    - title: 'Library'
      url: '/library/'


# Social Links
social:
- {icon: "ion-ios-business", color: "#0a243f", name: Strong Towns Homepage, link: "https://www.strongtowns.org"}
- {icon: "ion-ios-boat", color: "#00b9f1", name: Nanaimo Official City Plan, link: "https://www.nanaimo.ca/property-development/community-planning-land-use/city-plan"}
- {icon: "ion-ios-build", color: "#004475", name: Nanaimo City Projects, link: "https://www.nanaimo.ca/your-government/projects"}
- {icon: "ion-ios-bicycle", color: "#00668d", name: Get Involved Nanaimo, link: "https://www.getinvolvednanaimo.ca"}
- {icon: "ion-md-contacts", color: "#444444", name: Volunteer Nanaimo, link: "https://www.volunteernanaimo.ca"}

# Example of adding a new link to the footer - {icon: "ion-logo-youtube", color: "#ff0000", name: Youtube, link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: mleknryo  # Email generated from Formspree


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: strong-towns-nanaimo


#-------------------------------
# Google Analytics
# NOTE We're using Cloudflare instead...
google-analytics: # Add your GA Tracking Id